{- | Re-export of bnfc-autogenerated module -}
module Javalette.Syntax
  ( module Javalette.Syntax.AbsJavalette
  ) where

import Javalette.Syntax.AbsJavalette
import Javalette.Syntax.PrintJavalette hiding (Doc)

import Javalette.PrettyPrint

instance Pretty Prog where
  pPrint = pPrintConv

-- | Any type that implements `Print` can implement `pPrint` with this.
pPrintConv :: Print a => a -> Doc
pPrintConv = text . printTree
