{-# OPTIONS_GHC -fno-warn-orphans #-}
{- | Re-export of bnfc-autogenerated module -}
module Javalette.Syntax
  ( module Javalette.Syntax.AbsJavalette
  ) where

import Javalette.Syntax.AbsJavalette
import Javalette.Syntax.PrintJavalette hiding (Doc)

import Javalette.PrettyPrint

instance Pretty Ident where
  pPrint = pPrintConv

instance Pretty Prog where
  pPrint = pPrintConv

instance Pretty TopDef where
  pPrint = pPrintConv

instance Pretty Arg where
  pPrint = pPrintConv

instance Pretty Blk where
  pPrint = pPrintConv

instance Pretty Stmt where
  pPrint = pPrintConv

instance Pretty Item where
  pPrint = pPrintConv

instance Pretty Type where
  pPrint = pPrintConv

instance Pretty Expr where
  pPrint = pPrintConv

instance Pretty AddOp where
  pPrint = pPrintConv

instance Pretty MulOp where
  pPrint = pPrintConv

instance Pretty RelOp where
  pPrint = pPrintConv

instance Pretty LValue where
  pPrint = pPrintConv

instance Pretty Index where
  pPrint = pPrintConv

-- | Any type that implements `Print` can implement `pPrint` with this.
pPrintConv :: Print a => a -> Doc
pPrintConv = text . printTree
